//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTallerMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleTecnico
    {
        public string Descripcion { get; set; }
        public int detalleTecnicoID { get; set; }
        public Nullable<int> tecnicoID { get; set; }
        public Nullable<int> ordenServicioID { get; set; }
    
        public virtual OrdenServicio OrdenServicio { get; set; }
        public virtual Tecnico Tecnico { get; set; }
    }
}
