//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTallerMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleOrdenC
    {
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> Subtotal { get; set; }
        public int detalleOrdenCID { get; set; }
        public Nullable<int> materialID { get; set; }
        public Nullable<int> ordenCompraID { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual OrdenCompra OrdenCompra { get; set; }
    }
}
