//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTallerMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleServicio
    {
        public Nullable<int> Costo { get; set; }
        public Nullable<int> Tiempo { get; set; }
        public int detalleServicioID { get; set; }
        public Nullable<int> tipoServiciosID { get; set; }
        public Nullable<int> ordenServicioID { get; set; }
    
        public virtual OrdenServicio OrdenServicio { get; set; }
        public virtual TipoServicio TipoServicio { get; set; }
    }
}
