//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTallerMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Nit { get; set; }
        public Nullable<int> Nro { get; set; }
        public string RazonSocial { get; set; }
        public Nullable<int> Total { get; set; }
        public int facturaID { get; set; }
        public Nullable<int> ordenServicioID { get; set; }
    
        public virtual OrdenServicio OrdenServicio { get; set; }
    }
}
