//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTallerMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lugar
    {
        public Lugar()
        {
            this.OrdenServicios = new HashSet<OrdenServicio>();
        }
    
        public string Ciudad { get; set; }
        public string Lugar1 { get; set; }
        public int lugarID { get; set; }
    
        public virtual ICollection<OrdenServicio> OrdenServicios { get; set; }
    }
}
