//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTallerMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.DetalleOrdenCs = new HashSet<DetalleOrdenC>();
        }
    
        public string Descripcion { get; set; }
        public Nullable<int> Precio { get; set; }
        public int materialID { get; set; }
    
        public virtual ICollection<DetalleOrdenC> DetalleOrdenCs { get; set; }
    }
}
