//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTallerMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenCompra
    {
        public OrdenCompra()
        {
            this.DetalleOrdenCs = new HashSet<DetalleOrdenC>();
            this.OrdenServicios = new HashSet<OrdenServicio>();
        }
    
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Total { get; set; }
        public int ordenCompraID { get; set; }
    
        public virtual ICollection<DetalleOrdenC> DetalleOrdenCs { get; set; }
        public virtual ICollection<OrdenServicio> OrdenServicios { get; set; }
    }
}
