//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTallerMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenServicio
    {
        public OrdenServicio()
        {
            this.DetalleServicios = new HashSet<DetalleServicio>();
            this.DetalleTecnicoes = new HashSet<DetalleTecnico>();
            this.Facturas = new HashSet<Factura>();
        }
    
        public string Estado { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> Total { get; set; }
        public int ordenServicioID { get; set; }
        public Nullable<int> clienteID { get; set; }
        public Nullable<int> lugarID { get; set; }
        public Nullable<int> ordenCompraID { get; set; }
        public Nullable<int> vehiculoID { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<DetalleServicio> DetalleServicios { get; set; }
        public virtual ICollection<DetalleTecnico> DetalleTecnicoes { get; set; }
        public virtual ICollection<Factura> Facturas { get; set; }
        public virtual Lugar Lugar { get; set; }
        public virtual OrdenCompra OrdenCompra { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
