//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTallerMecanico.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbTallerEntities : DbContext
    {
        public dbTallerEntities()
            : base("name=dbTallerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<DetalleOrdenC> DetalleOrdenCs { get; set; }
        public virtual DbSet<DetalleServicio> DetalleServicios { get; set; }
        public virtual DbSet<DetalleTecnico> DetalleTecnicoes { get; set; }
        public virtual DbSet<Especialidad> Especialidads { get; set; }
        public virtual DbSet<Factura> Facturas { get; set; }
        public virtual DbSet<Lugar> Lugars { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<OrdenCompra> OrdenCompras { get; set; }
        public virtual DbSet<OrdenServicio> OrdenServicios { get; set; }
        public virtual DbSet<Tecnico> Tecnicoes { get; set; }
        public virtual DbSet<TipoServicio> TipoServicios { get; set; }
        public virtual DbSet<Vehiculo> Vehiculoes { get; set; }
    }
}
