//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTallerMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tecnico
    {
        public Tecnico()
        {
            this.DetalleTecnicoes = new HashSet<DetalleTecnico>();
        }
    
        public Nullable<int> Ci { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Telefono { get; set; }
        public int tecnicoID { get; set; }
        public Nullable<int> especialidadID { get; set; }
    
        public virtual ICollection<DetalleTecnico> DetalleTecnicoes { get; set; }
        public virtual Especialidad Especialidad { get; set; }
    }
}
