//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTallerMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoServicio
    {
        public TipoServicio()
        {
            this.DetalleServicios = new HashSet<DetalleServicio>();
        }
    
        public string Servicio { get; set; }
        public int tipoServiciosID { get; set; }
    
        public virtual ICollection<DetalleServicio> DetalleServicios { get; set; }
    }
}
