//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTallerMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        public Vehiculo()
        {
            this.OrdenServicios = new HashSet<OrdenServicio>();
        }
    
        public Nullable<int> Año { get; set; }
        public string Color { get; set; }
        public string Marca { get; set; }
        public string Matricula { get; set; }
        public string Modelo { get; set; }
        public string Observacion { get; set; }
        public int vehiculoID { get; set; }
    
        public virtual ICollection<OrdenServicio> OrdenServicios { get; set; }
    }
}
